CREATE TABLE PRODUTO (
    COD_PRODUTO CHAR(4) PRIMARY KEY NOT NULL,
    DES_PRODUTO VARCHAR(30),
    STA_STATUS CHAR(1)
);

CREATE TABLE PRODUTO_COSIF (
    COD_PRODUTO CHAR(4) NOT NULL,
    COD_COSIF CHAR(11) NOT NULL,
    COD_CLASSIFICACAO CHAR(6),
    STA_STATUS CHAR(1),
    PRIMARY KEY (COD_PRODUTO, COD_COSIF),
    FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);

CREATE TABLE MOVIMENTO_MANUAL (
    DAT_MES NUMERIC(2, 0) NOT NULL,
    DAT_ANO NUMERIC(4, 0) NOT NULL,
    NUM_LANCAMENTO NUMERIC(18, 0) NOT NULL,
    COD_COSIF CHAR(11) NOT NULL,
    COD_PRODUTO CHAR(4) NOT NULL,
    DES_DESCRICAO VARCHAR(50) NOT NULL,
    DAT_MOVIMENTO TIMESTAMP NOT NULL,
    COD_USUARIO VARCHAR(15) NOT NULL,
    VAL_VALOR NUMERIC(18, 2) NOT NULL,
    PRIMARY KEY (DAT_MES, DAT_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF),
    FOREIGN KEY (COD_PRODUTO, COD_COSIF) REFERENCES PRODUTO_COSIF(COD_PRODUTO, COD_COSIF)
);