INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES ('PRD1', 'DESC001', 'A');
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES ('PRD2', 'DESC002', 'A');
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) VALUES ('PRD2', 'COSIF01', 'TESTE1', 'A');
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) VALUES ('PRD1', 'COSIF02', 'TESTE2', 'A');
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) VALUES ('PRD2', 'COSIF03', 'TESTE3', 'A');
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) VALUES ('PRD1', 'COSIF04', 'TESTE4', 'A');